# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainScreeen(object):
    def setupUi(self, mainScreeen):
        mainScreeen.setObjectName("mainScreeen")
        mainScreeen.resize(380, 520)
        mainScreeen.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(mainScreeen)
        self.centralwidget.setObjectName("centralwidget")
        self.mainTitle = QtWidgets.QLabel(self.centralwidget)
        self.mainTitle.setGeometry(QtCore.QRect(70, 60, 301, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(19)
        self.mainTitle.setFont(font)
        self.mainTitle.setObjectName("mainTitle")


        self.detectButton = QtWidgets.QPushButton(self.centralwidget)
        self.detectButton.setGeometry(QtCore.QRect(100, 170, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.detectButton.setFont(font)
        self.detectButton.setObjectName("detectButton")

        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(100, 370, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")


        self.guideButton = QtWidgets.QPushButton(self.centralwidget)
        self.guideButton.setGeometry(QtCore.QRect(100, 270, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.guideButton.setFont(font)
        self.guideButton.setObjectName("guideButton")
        
        mainScreeen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainScreeen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        mainScreeen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainScreeen)
        self.statusbar.setObjectName("statusbar")
        mainScreeen.setStatusBar(self.statusbar)

        self.retranslateUi(mainScreeen)
        QtCore.QMetaObject.connectSlotsByName(mainScreeen)

    def retranslateUi(self, mainScreeen):
        _translate = QtCore.QCoreApplication.translate
        mainScreeen.setWindowTitle(_translate("mainScreeen", "Detection Tool"))
        self.mainTitle.setText(_translate("mainScreeen", "  Hand Grasp Detector "))
        self.detectButton.setText(_translate("mainScreeen", "Detect"))
        self.exitButton.setText(_translate("mainScreeen", "Exit"))
        self.guideButton.setText(_translate("mainScreeen", "How to use guide"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainScreeen = QtWidgets.QMainWindow()
    ui = Ui_mainScreeen()
    ui.setupUi(mainScreeen)
    mainScreeen.show()
    sys.exit(app.exec_())
